import type { NextPage } from 'next'
import Head from 'next/head'
import SignUpForm from './components/SignUpForm'
import Navigation from './components/Navigation'
import Footer from './components/Footer'

const SignUp: NextPage = () => {
    return (
        <div>
            <Head>
                <title>SyntropicA - Community Food Forests and Permaculture in Aruba</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />   
            <SignUpForm email={"8526796d07117307ff97b7005eb6b6b9"} />            
            <Footer />
        </div>
    )
}

export default SignUp
